version: "3.9"
services:
  web:
    build: .
    image: meteoro-shiny
    volumes:
      - ./apps:/srv/shiny-server/
      - ./log:/var/log/shiny-server/
    ports:
      - "5050:5050"
    networks:
      - backend
    
  postgres:
    image: postgres:14-alpine
    ports:
      - 5430:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - backend


networks:
  backend: